name: Test workflow

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode'
        required: false
        type: boolean
        default: true

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  test-job-1:
    name: Test job 1
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false # Keeps a new job pending until an existing job completes

    env:
      DRY_RUN: ${{ inputs.dry-run && 'echo' || '' }}

    steps:
      - name: Print inputs
        run: |
          echo "Dry run: ${{ inputs.dry-run }}"

      - name: Print context
        uses: actions/github-script@v7
        with:
          script: |
            // Print the context
            console.log('Context:', context);

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        env:
          LIST_GIT: ${{ inputs.dry-run && '.git' || '' }}
        run: |
          set -x
          echo "LIST_GIT: $LIST_GIT"
          echo "Listing files regardless of dry-run:"
          ls -l ${LIST_GIT:-} \
            .github ${{ inputs.dry-run && '|| true' || '' }}
 
           if [ "${{ inputs.dry-run }}" = "true" ]; then
            echo "Dry run is enabled."
          fi

          echo "Listing files only if not dry-run:"
          $DRY_RUN ls -l ${LIST_GIT:-} .github

      - name: Report success
        if: success()
        run: echo "All steps completed successfully."

      - name: Report failure
        if: failure()
        run: echo "One or more steps failed."
